import { DateIdea } from "./types";

export const dateIdeas: DateIdea[] = [
  // ===== ARTS & CRAFTS =====
  {
    id: "pottery",
    title: "Pottery Class",
    description: "Get your hands dirty making ceramics together. Beginner-friendly classes where you'll shape, glaze, and fire your creations.",
    emoji: "🏺",
    budget: ["under75"],
    vibe: ["creative", "romantic"],
    setting: "indoor",
    location: ["jersey-city", "hoboken", "manhattan"],
    dateType: "arts-crafts",
    venues: [
      { name: "Color Me Mine", address: "225 Liberty St, New York, NY 10281", rating: 5, priceRange: "$45-65/person", googleMapsUrl: "https://maps.google.com/?q=Color+Me+Mine+Brookfield+Place+NYC", highlight: "Walk-in friendly, great for beginners, Brookfield Place location" },
      { name: "Pottery Row", address: "19 W 21st St, New York, NY 10010", rating: 5, priceRange: "$50-80/person", googleMapsUrl: "https://maps.google.com/?q=Pottery+Row+NYC", website: "https://www.potteryrow.com", highlight: "Intimate couples classes, BYOB, wheel throwing focus" },
      { name: "Choplet", address: "309 3rd Ave, Brooklyn, NY 11215", rating: 4, priceRange: "$55-75/person", googleMapsUrl: "https://maps.google.com/?q=Choplet+Brooklyn", highlight: "Beautiful studio, great instructors, easy PATH ride from JC" },
      { name: "Classpop! Studios", address: "Jersey City, NJ", rating: 4, priceRange: "$40-60/person", googleMapsUrl: "https://maps.google.com/?q=pottery+class+Jersey+City+NJ", highlight: "Local JC option, various locations, flexible scheduling" },
      { name: "The Mud Room", address: "Hoboken, NJ", rating: 4, priceRange: "$45-65/person", googleMapsUrl: "https://maps.google.com/?q=pottery+class+Hoboken+NJ", highlight: "Walkable from JC, relaxed vibe, date night specials" },
    ],
  },
  {
    id: "paint-sip",
    title: "Paint & Sip Night",
    description: "Follow an instructor, sip wine, and paint on canvas. No talent required — just laughs and a masterpiece to take home.",
    emoji: "🎨",
    budget: ["under75"],
    vibe: ["creative", "cozy", "romantic"],
    setting: "indoor",
    location: ["jersey-city", "hoboken", "manhattan"],
    dateType: "arts-crafts",
    venues: [
      { name: "Muse Paintbar", address: "233 Washington St, Hoboken, NJ 07030", rating: 5, priceRange: "$35-50/person", googleMapsUrl: "https://maps.google.com/?q=Muse+Paintbar+Hoboken", website: "https://www.musepaintbar.com", highlight: "Best paint & sip nearby, full bar, great instructors" },
      { name: "Painting with a Twist", address: "Jersey City area", rating: 4, priceRange: "$35-45/person", googleMapsUrl: "https://maps.google.com/?q=Painting+with+a+Twist+Jersey+City", highlight: "BYOB-friendly, date night themes every weekend" },
      { name: "Pinot's Palette", address: "Hoboken, NJ", rating: 4, priceRange: "$35-50/person", googleMapsUrl: "https://maps.google.com/?q=Pinots+Palette+Hoboken+NJ", highlight: "Cozy atmosphere, couples canvases available" },
      { name: "Paint Lounge NYC", address: "Various Manhattan locations", rating: 4, priceRange: "$40-55/person", googleMapsUrl: "https://maps.google.com/?q=Paint+Lounge+NYC", highlight: "Open studio concept — paint whatever you want, no class structure" },
    ],
  },
  {
    id: "flower-arranging",
    title: "Flower Arranging Workshop",
    description: "Learn to create beautiful bouquets together. Take home your arrangements and fill your place with fresh flowers.",
    emoji: "💐",
    budget: ["under75", "splurge"],
    vibe: ["creative", "romantic"],
    setting: "indoor",
    location: ["manhattan", "jersey-city"],
    dateType: "arts-crafts",
    venues: [
      { name: "FlowerSchool New York", address: "213 W 14th St, New York, NY 10011", rating: 5, priceRange: "$85-125/person", googleMapsUrl: "https://maps.google.com/?q=FlowerSchool+New+York", website: "https://www.flowerschoolny.com", highlight: "Top-rated, gorgeous Chelsea location, seasonal arrangements" },
      { name: "Buunch Floral Workshop", address: "Manhattan, NY", rating: 5, priceRange: "$75-100/person", googleMapsUrl: "https://maps.google.com/?q=Buunch+Floral+Workshop+NYC", highlight: "Small intimate classes, stunning designs, great for couples" },
      { name: "Local JC florists", address: "Jersey City, NJ", rating: 3, priceRange: "$50-75/person", googleMapsUrl: "https://maps.google.com/?q=flower+arranging+class+Jersey+City", highlight: "Check seasonal workshops at local flower shops" },
    ],
  },

  // ===== DINING =====
  {
    id: "italian-dinner",
    title: "Italian Dinner Date",
    description: "Classic romance — candlelight, pasta, wine, and conversation. Nothing beats a great Italian restaurant for date night.",
    emoji: "🍝",
    budget: ["under75", "splurge"],
    vibe: ["romantic", "cozy"],
    setting: "indoor",
    location: ["jersey-city", "manhattan", "hoboken"],
    dateType: "dining",
    venues: [
      { name: "Razza", address: "275-277 Grove St, Jersey City, NJ 07302", rating: 5, priceRange: "$40-65/couple", googleMapsUrl: "https://maps.google.com/?q=Razza+Pizza+Jersey+City", highlight: "Best pizza in NJ, house-milled flour, natural wine list" },
      { name: "Porto Leggero", address: "185 Hudson St, Jersey City, NJ 07311", rating: 5, priceRange: "$100-160/couple", googleMapsUrl: "https://maps.google.com/?q=Porto+Leggero+Jersey+City", highlight: "Waterfront, chandeliers, Manhattan skyline views" },
      { name: "Corto", address: "464 Central Ave, Jersey City, NJ 07307", rating: 4, priceRange: "$40-60/couple", googleMapsUrl: "https://maps.google.com/?q=Corto+Jersey+City", highlight: "Rustic & authentic, BYOB, cozy Heights gem" },
      { name: "Carmine's", address: "200 W 44th St, New York, NY 10036", rating: 4, priceRange: "$60-90/couple", googleMapsUrl: "https://maps.google.com/?q=Carmines+Times+Square+NYC", highlight: "Massive family-style portions, classic NYC Italian" },
      { name: "L'Artusi", address: "228 W 10th St, New York, NY 10014", rating: 5, priceRange: "$100-140/couple", googleMapsUrl: "https://maps.google.com/?q=LArtusi+NYC", website: "https://www.lartusi.com", highlight: "West Village gem, modern Italian, incredible pasta" },
    ],
  },
  {
    id: "sushi-omakase",
    title: "Sushi & Omakase Experience",
    description: "Sit at the bar and let the chef surprise you with the freshest fish. An intimate, luxurious dining experience.",
    emoji: "🍣",
    budget: ["splurge"],
    vibe: ["romantic", "adventurous"],
    setting: "indoor",
    location: ["jersey-city", "manhattan"],
    dateType: "dining",
    venues: [
      { name: "DOMO DOMO", address: "105 Greene St, Jersey City, NJ 07302", rating: 5, priceRange: "$120-200/couple", googleMapsUrl: "https://maps.google.com/?q=DOMO+DOMO+Jersey+City", highlight: "JC's best sushi, DOMOKASE tasting is unforgettable" },
      { name: "Sushi Nakazawa", address: "23 Commerce St, New York, NY 10014", rating: 5, priceRange: "$150-250/couple", googleMapsUrl: "https://maps.google.com/?q=Sushi+Nakazawa+NYC", highlight: "Jiro Dreams of Sushi alum, West Village, world-class" },
      { name: "Sugarfish", address: "Various Manhattan locations", rating: 4, priceRange: "$80-120/couple", googleMapsUrl: "https://maps.google.com/?q=Sugarfish+Manhattan", highlight: "Trust Me menu, consistently excellent, no reservations needed" },
      { name: "Kissaki", address: "Various Manhattan locations", rating: 4, priceRange: "$100-160/couple", googleMapsUrl: "https://maps.google.com/?q=Kissaki+NYC", highlight: "Beautiful plating, intimate atmosphere, omakase at every price point" },
    ],
  },
  {
    id: "brunch",
    title: "Weekend Brunch Date",
    description: "Lazy mornings, great food, and bottomless mimosas. The ultimate low-key date for when you want to take it easy.",
    emoji: "🥞",
    budget: ["under25", "under75"],
    vibe: ["cozy", "romantic"],
    setting: "indoor",
    location: ["jersey-city", "hoboken", "manhattan"],
    dateType: "dining",
    venues: [
      { name: "Hamilton Pork", address: "247 10th St, Jersey City, NJ 07302", rating: 5, priceRange: "$20-40/couple", googleMapsUrl: "https://maps.google.com/?q=Hamilton+Pork+Jersey+City", highlight: "Legendary JC brunch, bloody mary flights, creative dishes" },
      { name: "Thirty Acres", address: "500 Jersey Ave, Jersey City, NJ 07302", rating: 5, priceRange: "$30-50/couple", googleMapsUrl: "https://maps.google.com/?q=Thirty+Acres+Jersey+City", highlight: "Chef-driven, seasonal menu, intimate space" },
      { name: "Toastique", address: "Hoboken, NJ", rating: 4, priceRange: "$20-35/couple", googleMapsUrl: "https://maps.google.com/?q=Toastique+Hoboken", highlight: "Beautiful toast creations, healthy & Instagram-worthy" },
      { name: "Bubby's", address: "120 Hudson St, New York, NY 10013", rating: 4, priceRange: "$30-50/couple", googleMapsUrl: "https://maps.google.com/?q=Bubbys+Tribeca+NYC", highlight: "Tribeca classic, pancakes & pie, cozy Americana" },
      { name: "Jack's Wife Freda", address: "Various Manhattan locations", rating: 4, priceRange: "$30-50/couple", googleMapsUrl: "https://maps.google.com/?q=Jacks+Wife+Freda+NYC", highlight: "Mediterranean brunch, vibrant, always delicious" },
    ],
  },
  {
    id: "food-hall",
    title: "Food Hall Crawl",
    description: "Share small bites from different vendors — tacos, dumplings, pizza, dessert. Try a little of everything together.",
    emoji: "🌮",
    budget: ["under25", "under75"],
    vibe: ["adventurous", "active"],
    setting: "indoor",
    location: ["jersey-city", "manhattan"],
    dateType: "food-experience",
    venues: [
      { name: "Urby Market", address: "200 Greene St, Jersey City, NJ 07311", rating: 4, priceRange: "$20-40/couple", googleMapsUrl: "https://maps.google.com/?q=Urby+Jersey+City", highlight: "Local JC food hall, diverse vendors, waterfront area" },
      { name: "Chelsea Market", address: "75 9th Ave, New York, NY 10011", rating: 5, priceRange: "$25-50/couple", googleMapsUrl: "https://maps.google.com/?q=Chelsea+Market+NYC", highlight: "Iconic NYC food hall, lobster, tacos, baked goods, everything" },
      { name: "Brookfield Place", address: "230 Vesey St, New York, NY 10281", rating: 4, priceRange: "$25-50/couple", googleMapsUrl: "https://maps.google.com/?q=Brookfield+Place+NYC", highlight: "Right off the PATH, Hudson Eats has great variety" },
      { name: "Urbanspace Vanderbilt", address: "230 Park Ave, New York, NY 10169", rating: 4, priceRange: "$20-40/couple", googleMapsUrl: "https://maps.google.com/?q=Urbanspace+Vanderbilt+NYC", highlight: "Near Grand Central, tons of options, fun energy" },
    ],
  },

  // ===== DRINKS =====
  {
    id: "speakeasy",
    title: "Speakeasy Cocktail Night",
    description: "Discover hidden bars with craft cocktails. Dress up, find the secret entrance, and feel like you're in the 1920s.",
    emoji: "🥃",
    budget: ["under75"],
    vibe: ["romantic", "adventurous"],
    setting: "indoor",
    location: ["jersey-city", "manhattan"],
    dateType: "drinks",
    venues: [
      { name: "Madame", address: "337 Newark Ave, Jersey City, NJ 07302", rating: 5, priceRange: "$40-70/couple", googleMapsUrl: "https://maps.google.com/?q=Madame+Bar+Jersey+City", highlight: "French cocktail parlor, feels like Paris, stunning interior" },
      { name: "Cellar 335", address: "335 Newark Ave, Jersey City, NJ 07302", rating: 5, priceRange: "$40-65/couple", googleMapsUrl: "https://maps.google.com/?q=Cellar+335+Jersey+City", highlight: "Tiki cocktails, Asian-fusion bites, underground vibe" },
      { name: "Please Don't Tell (PDT)", address: "113 St Marks Pl, New York, NY 10009", rating: 5, priceRange: "$50-80/couple", googleMapsUrl: "https://maps.google.com/?q=Please+Dont+Tell+PDT+NYC", highlight: "Enter through a phone booth in a hot dog shop — legendary" },
      { name: "Attaboy", address: "134 Eldridge St, New York, NY 10002", rating: 5, priceRange: "$50-80/couple", googleMapsUrl: "https://maps.google.com/?q=Attaboy+NYC", highlight: "No menu — bartenders make drinks based on your mood" },
      { name: "Death & Co", address: "433 E 6th St, New York, NY 10009", rating: 5, priceRange: "$50-80/couple", googleMapsUrl: "https://maps.google.com/?q=Death+and+Co+NYC", highlight: "Dark, intimate, cocktails are pure art" },
    ],
  },
  {
    id: "wine-tasting",
    title: "Wine Tasting",
    description: "Share a wine flight, learn about different varietals, and discover your favorites together. Classy and romantic.",
    emoji: "🍷",
    budget: ["under75", "splurge"],
    vibe: ["romantic", "cozy"],
    setting: "indoor",
    location: ["jersey-city", "manhattan"],
    dateType: "drinks",
    venues: [
      { name: "City Vineyard", address: "233 West St, New York, NY 10013", rating: 5, priceRange: "$50-80/couple", googleMapsUrl: "https://maps.google.com/?q=City+Vineyard+NYC", highlight: "Rooftop with Hudson River views, wine flights, cheese boards" },
      { name: "Aldo Sohm Wine Bar", address: "151 W 51st St, New York, NY 10019", rating: 5, priceRange: "$60-100/couple", googleMapsUrl: "https://maps.google.com/?q=Aldo+Sohm+Wine+Bar+NYC", highlight: "World-class sommelier, elegant midtown spot" },
      { name: "Cork City", address: "Jersey City, NJ", rating: 4, priceRange: "$30-50/couple", googleMapsUrl: "https://maps.google.com/?q=wine+bar+Jersey+City+NJ", highlight: "Local JC wine bar, cozy, great selection" },
      { name: "Corkbuzz", address: "13 E 13th St, New York, NY 10003", rating: 4, priceRange: "$50-80/couple", googleMapsUrl: "https://maps.google.com/?q=Corkbuzz+NYC", highlight: "Master Sommelier owner, fun educational approach" },
    ],
  },
  {
    id: "craft-beer",
    title: "Craft Beer Tasting",
    description: "Sample local brews, compare tasting notes, and enjoy a relaxed evening at a taproom.",
    emoji: "🍺",
    budget: ["under25"],
    vibe: ["cozy", "active"],
    setting: "indoor",
    location: ["jersey-city", "hoboken"],
    dateType: "drinks",
    venues: [
      { name: "Departed Soles Brewing", address: "150 Bay St, Jersey City, NJ 07302", rating: 5, priceRange: "$15-30/couple", googleMapsUrl: "https://maps.google.com/?q=Departed+Soles+Brewing+Jersey+City", highlight: "JC's beloved gluten-free brewery, games, great vibes" },
      { name: "Barcade", address: "163 Newark Ave, Jersey City, NJ 07302", rating: 4, priceRange: "$15-30/couple", googleMapsUrl: "https://maps.google.com/?q=Barcade+Jersey+City", highlight: "Retro arcade games + craft beer = perfect combo" },
      { name: "902 Brewing", address: "101 Pacific Ave, Jersey City, NJ 07304", rating: 4, priceRange: "$15-25/couple", googleMapsUrl: "https://maps.google.com/?q=902+Brewing+Jersey+City", highlight: "Small-batch local brews, chill taproom" },
      { name: "Hoboken Brewing Co", address: "Hoboken, NJ", rating: 4, priceRange: "$15-30/couple", googleMapsUrl: "https://maps.google.com/?q=Hoboken+Brewing+Company", highlight: "Walkable from JC, solid lineup, weekend specials" },
    ],
  },
  {
    id: "rooftop-drinks",
    title: "Rooftop Drinks at Sunset",
    description: "Cocktails with a view. Watch the sun set over the skyline from a stunning rooftop bar.",
    emoji: "🌇",
    budget: ["under75", "splurge"],
    vibe: ["romantic"],
    setting: "outdoor",
    location: ["jersey-city", "manhattan"],
    dateType: "drinks",
    venues: [
      { name: "Rooftop at Exchange Place", address: "Exchange Place, Jersey City, NJ", rating: 5, priceRange: "$40-70/couple", googleMapsUrl: "https://maps.google.com/?q=rooftop+bar+Exchange+Place+Jersey+City", highlight: "Manhattan skyline panorama, best sunset views from JC side" },
      { name: "Westlight", address: "111 N 12th St, Brooklyn, NY 11249", rating: 5, priceRange: "$50-80/couple", googleMapsUrl: "https://maps.google.com/?q=Westlight+Brooklyn", highlight: "360-degree views, stunning cocktails, William Vale Hotel" },
      { name: "230 Fifth", address: "230 5th Ave, New York, NY 10001", rating: 4, priceRange: "$40-70/couple", googleMapsUrl: "https://maps.google.com/?q=230+Fifth+Rooftop+NYC", highlight: "Empire State Building views, iconic, great for photos" },
      { name: "The Crown", address: "50 Bowery, New York, NY 10013", rating: 4, priceRange: "$50-80/couple", googleMapsUrl: "https://maps.google.com/?q=The+Crown+Bowery+NYC", highlight: "Hotel 50 Bowery rooftop, Chinatown views, craft cocktails" },
    ],
  },

  // ===== ADVENTURE =====
  {
    id: "escape-room",
    title: "Escape Room Challenge",
    description: "Solve puzzles, crack codes, and escape together before time runs out. Great for teamwork and competitive couples.",
    emoji: "🔐",
    budget: ["under75"],
    vibe: ["active", "adventurous"],
    setting: "indoor",
    location: ["jersey-city", "manhattan"],
    dateType: "adventure",
    venues: [
      { name: "Puzzle Out", address: "321 Newark Ave, Jersey City, NJ 07302", rating: 5, priceRange: "$50-70/couple", googleMapsUrl: "https://maps.google.com/?q=Puzzle+Out+Jersey+City", highlight: "Best in JC, multiple themed rooms, challenging puzzles" },
      { name: "Mission Escape Games", address: "15 Sip Ave, Jersey City, NJ 07306", rating: 4, priceRange: "$50-70/couple", googleMapsUrl: "https://maps.google.com/?q=Mission+Escape+Games+Jersey+City", highlight: "Immersive rooms, good for first-timers" },
      { name: "The Escape Game NYC", address: "295 Madison Ave, New York, NY 10017", rating: 5, priceRange: "$60-80/couple", googleMapsUrl: "https://maps.google.com/?q=The+Escape+Game+NYC", highlight: "Premium production quality, Midtown, multiple themes" },
      { name: "BEAT THE BOMB", address: "550 Washington Blvd, Jersey City, NJ", rating: 5, priceRange: "$50-70/couple", googleMapsUrl: "https://maps.google.com/?q=Beat+The+Bomb+Jersey+City", highlight: "Paint bomb finale, immersive tech, super unique" },
    ],
  },
  {
    id: "go-karts",
    title: "Go-Kart Racing",
    description: "Electric go-karts on multi-level tracks. Race each other, talk trash, and let your competitive sides out!",
    emoji: "🏎️",
    budget: ["under75"],
    vibe: ["active", "adventurous"],
    setting: "indoor",
    location: ["jersey-city"],
    dateType: "adventure",
    venues: [
      { name: "RPM Raceway", address: "99 Caven Point Rd, Jersey City, NJ 07305", rating: 5, priceRange: "$40-60/couple", googleMapsUrl: "https://maps.google.com/?q=RPM+Raceway+Jersey+City", highlight: "Multi-level tracks, VR arcade, full snack bar" },
      { name: "K1 Speed", address: "Linden, NJ (30min from JC)", rating: 4, priceRange: "$40-60/couple", googleMapsUrl: "https://maps.google.com/?q=K1+Speed+Linden+NJ", highlight: "Pro-level electric karts, great track design" },
    ],
  },
  {
    id: "rock-climbing",
    title: "Indoor Rock Climbing",
    description: "Belay each other, push your limits, and cheer each other on. Great workout and great bonding.",
    emoji: "🧗",
    budget: ["under75"],
    vibe: ["active", "adventurous"],
    setting: "indoor",
    location: ["jersey-city", "manhattan", "hoboken"],
    dateType: "adventure",
    venues: [
      { name: "The Gravity Vault", address: "Hoboken/Upper Montclair, NJ", rating: 5, priceRange: "$30-50/couple", googleMapsUrl: "https://maps.google.com/?q=Gravity+Vault+Hoboken", highlight: "Great bouldering, close to JC, beginner-friendly" },
      { name: "Brooklyn Boulders", address: "575 Degraw St, Brooklyn, NY 11217", rating: 5, priceRange: "$40-60/couple", googleMapsUrl: "https://maps.google.com/?q=Brooklyn+Boulders", highlight: "Massive gym, ropes & bouldering, cool community" },
      { name: "The Cliffs at LIC", address: "11-11 44th Dr, Long Island City, NY", rating: 4, priceRange: "$40-55/couple", googleMapsUrl: "https://maps.google.com/?q=The+Cliffs+LIC", highlight: "Huge facility, yoga too, great for a full active date" },
    ],
  },
  {
    id: "hot-tub-boat",
    title: "Hot Tub Boat Cruise",
    description: "Yes, really — a hot tub on a boat. Cruise the Hudson with Manhattan skyline views while soaking in warm water.",
    emoji: "🛁",
    budget: ["splurge"],
    vibe: ["romantic", "adventurous"],
    setting: "outdoor",
    location: ["jersey-city"],
    dateType: "adventure",
    venues: [
      { name: "Sea the City", address: "Liberty Landing Marina, Jersey City, NJ 07305", rating: 5, priceRange: "$100-180/couple", googleMapsUrl: "https://maps.google.com/?q=Sea+the+City+Liberty+Landing+Marina", website: "https://www.seathecity.com", highlight: "90-min cruise, Statue of Liberty views, BYOB, unforgettable" },
    ],
  },

  // ===== ENTERTAINMENT =====
  {
    id: "live-music",
    title: "Live Music Night",
    description: "Catch a concert, jazz set, or open mic together. Let the music set the mood for an unforgettable evening.",
    emoji: "🎵",
    budget: ["under25", "under75"],
    vibe: ["romantic", "adventurous", "active"],
    setting: "indoor",
    location: ["jersey-city", "manhattan"],
    dateType: "entertainment",
    venues: [
      { name: "White Eagle Hall", address: "337 Newark Ave, Jersey City, NJ 07302", rating: 5, priceRange: "$15-50/person", googleMapsUrl: "https://maps.google.com/?q=White+Eagle+Hall+Jersey+City", highlight: "JC's premier venue, intimate shows, amazing sound" },
      { name: "Blue Note Jazz Club", address: "131 W 3rd St, New York, NY 10012", rating: 5, priceRange: "$30-60/person", googleMapsUrl: "https://maps.google.com/?q=Blue+Note+Jazz+Club+NYC", highlight: "Legendary jazz, world-class artists, Greenwich Village" },
      { name: "Village Vanguard", address: "178 7th Ave S, New York, NY 10014", rating: 5, priceRange: "$30-50/person", googleMapsUrl: "https://maps.google.com/?q=Village+Vanguard+NYC", highlight: "Historic jazz club since 1935, intimate, pure magic" },
      { name: "FM", address: "340 3rd St, Jersey City, NJ 07302", rating: 4, priceRange: "$10-20/person", googleMapsUrl: "https://maps.google.com/?q=FM+Jersey+City", highlight: "Dive bar vibes, local bands, cheap drinks, JC favorite" },
    ],
  },
  {
    id: "comedy-show",
    title: "Comedy Show",
    description: "Laugh together at a stand-up show. From open mics to big-name comedians — there's always something playing.",
    emoji: "😂",
    budget: ["under25", "under75"],
    vibe: ["active", "cozy"],
    setting: "indoor",
    location: ["manhattan", "jersey-city"],
    dateType: "entertainment",
    venues: [
      { name: "Comedy Cellar", address: "117 MacDougal St, New York, NY 10012", rating: 5, priceRange: "$20-30/person", googleMapsUrl: "https://maps.google.com/?q=Comedy+Cellar+NYC", highlight: "THE comedy club, surprise A-list drop-ins, legendary" },
      { name: "Gotham Comedy Club", address: "208 W 23rd St, New York, NY 10011", rating: 4, priceRange: "$20-30/person", googleMapsUrl: "https://maps.google.com/?q=Gotham+Comedy+Club+NYC", highlight: "Upscale club feel, consistently great lineups" },
      { name: "The Stand", address: "116 E 16th St, New York, NY 10003", rating: 4, priceRange: "$20-35/person", googleMapsUrl: "https://maps.google.com/?q=The+Stand+NYC", highlight: "Great dinner + show packages, intimate" },
      { name: "Open mics in JC", address: "Various JC venues", rating: 3, priceRange: "$5-15/person", googleMapsUrl: "https://maps.google.com/?q=comedy+open+mic+Jersey+City", highlight: "Free/cheap, support local talent, anything can happen" },
    ],
  },
  {
    id: "bowling",
    title: "Bowling & Arcade Night",
    description: "Classic date energy — bowl, play arcade games, share nachos. Casual, fun, and never gets old.",
    emoji: "🎳",
    budget: ["under25", "under75"],
    vibe: ["active", "cozy"],
    setting: "indoor",
    location: ["jersey-city", "manhattan"],
    dateType: "entertainment",
    venues: [
      { name: "Bowlero", address: "Jersey City area", rating: 4, priceRange: "$20-40/couple", googleMapsUrl: "https://maps.google.com/?q=Bowlero+near+Jersey+City", highlight: "Glow bowling, arcade, full bar, late-night hours" },
      { name: "Brooklyn Bowl", address: "61 Wythe Ave, Brooklyn, NY 11249", rating: 5, priceRange: "$30-50/couple", googleMapsUrl: "https://maps.google.com/?q=Brooklyn+Bowl", highlight: "Live music + bowling + Blue Ribbon fried chicken" },
      { name: "Frames NYC", address: "550 9th Ave, New York, NY 10018", rating: 4, priceRange: "$25-45/couple", googleMapsUrl: "https://maps.google.com/?q=Frames+Bowling+NYC", highlight: "Hell's Kitchen, DJ nights, upscale bowling" },
    ],
  },
  {
    id: "karaoke",
    title: "Karaoke Night",
    description: "Belt out your favorite duets in a private room. Terrible singing encouraged. It's all about having fun.",
    emoji: "🎤",
    budget: ["under25", "under75"],
    vibe: ["active", "adventurous"],
    setting: "indoor",
    location: ["jersey-city", "manhattan"],
    dateType: "entertainment",
    venues: [
      { name: "Karaoke Duet", address: "Various Manhattan locations", rating: 5, priceRange: "$20-40/couple/hr", googleMapsUrl: "https://maps.google.com/?q=Karaoke+Duet+NYC", highlight: "Private rooms, huge song selection, BYOB snacks" },
      { name: "Gagopa Karaoke", address: "28 W 32nd St, New York, NY 10001", rating: 4, priceRange: "$25-45/couple/hr", googleMapsUrl: "https://maps.google.com/?q=Gagopa+Karaoke+NYC", highlight: "K-town classic, great sound system, open late" },
      { name: "JC karaoke bars", address: "Newark Ave, Jersey City, NJ", rating: 3, priceRange: "$15-30/couple", googleMapsUrl: "https://maps.google.com/?q=karaoke+Jersey+City+NJ", highlight: "Bar-style karaoke, cheaper, more spontaneous" },
    ],
  },

  // ===== OUTDOORS =====
  {
    id: "waterfront-walk",
    title: "Waterfront Sunset Walk",
    description: "Walk the JC waterfront with Statue of Liberty and Manhattan skyline views. Simple, free, and deeply romantic.",
    emoji: "🌅",
    budget: ["free"],
    vibe: ["romantic", "cozy"],
    setting: "outdoor",
    location: ["jersey-city"],
    dateType: "outdoors",
    venues: [
      { name: "Liberty State Park", address: "200 Morris Pesin Dr, Jersey City, NJ 07305", rating: 5, priceRange: "Free", googleMapsUrl: "https://maps.google.com/?q=Liberty+State+Park+Jersey+City", highlight: "Statue of Liberty views, huge park, best sunsets" },
      { name: "Hudson River Waterfront Walkway", address: "Jersey City Waterfront, NJ", rating: 5, priceRange: "Free", googleMapsUrl: "https://maps.google.com/?q=Hudson+River+Waterfront+Walkway+Jersey+City", highlight: "Miles of paved path, skyline the whole way" },
      { name: "Paulus Hook", address: "Paulus Hook, Jersey City, NJ", rating: 4, priceRange: "Free", googleMapsUrl: "https://maps.google.com/?q=Paulus+Hook+Jersey+City", highlight: "Charming cobblestone neighborhood, great photo spots" },
    ],
  },
  {
    id: "bike-ride",
    title: "Bike Ride & Ice Cream",
    description: "Rent Citi Bikes, explore the waterfront, and reward yourselves with ice cream. Simple, active, sweet.",
    emoji: "🚲",
    budget: ["under25"],
    vibe: ["active", "romantic"],
    setting: "outdoor",
    location: ["jersey-city", "manhattan"],
    dateType: "outdoors",
    venues: [
      { name: "Hudson River Waterfront Path", address: "Jersey City, NJ", rating: 5, priceRange: "$5-15/couple", googleMapsUrl: "https://maps.google.com/?q=Hudson+River+Waterfront+Walkway+Jersey+City", highlight: "Citi Bike along the water, skyline views the whole way" },
      { name: "Central Park Loop", address: "Central Park, New York, NY", rating: 5, priceRange: "$5-15/couple", googleMapsUrl: "https://maps.google.com/?q=Central+Park+bike+ride", highlight: "Classic NYC, 6-mile loop, gorgeous any season" },
      { name: "Brooklyn Bridge to DUMBO", address: "Brooklyn Bridge, NY", rating: 5, priceRange: "$5-15/couple", googleMapsUrl: "https://maps.google.com/?q=Brooklyn+Bridge+bike+ride", highlight: "Iconic views, stop for pizza in DUMBO after" },
    ],
  },
  {
    id: "picnic",
    title: "Park Picnic",
    description: "Pack a blanket, cheese, wine, and your favorite snacks. Find a beautiful park and just be together.",
    emoji: "🧺",
    budget: ["free", "under25"],
    vibe: ["romantic", "cozy"],
    setting: "outdoor",
    location: ["jersey-city", "manhattan"],
    dateType: "outdoors",
    venues: [
      { name: "Hamilton Park", address: "Jersey City, NJ 07302", rating: 5, priceRange: "Free-$25", googleMapsUrl: "https://maps.google.com/?q=Hamilton+Park+Jersey+City", highlight: "Tree-lined, charming, great people-watching in downtown JC" },
      { name: "Liberty State Park", address: "200 Morris Pesin Dr, Jersey City, NJ 07305", rating: 5, priceRange: "Free-$25", googleMapsUrl: "https://maps.google.com/?q=Liberty+State+Park+Jersey+City", highlight: "Spacious waterfront, Statue of Liberty backdrop" },
      { name: "Central Park Sheep Meadow", address: "Central Park, New York, NY", rating: 5, priceRange: "Free-$25", googleMapsUrl: "https://maps.google.com/?q=Sheep+Meadow+Central+Park", highlight: "Classic NYC, skyline views, perfect spring/summer" },
      { name: "Bryant Park", address: "41 W 40th St, New York, NY 10018", rating: 4, priceRange: "Free-$25", googleMapsUrl: "https://maps.google.com/?q=Bryant+Park+NYC", highlight: "Midtown oasis, cafe nearby, great for quick picnic" },
    ],
  },
  {
    id: "ferry-statue",
    title: "Ferry to Statue of Liberty",
    description: "Take the ferry from JC to Liberty Island. Walk around the statue, take iconic photos, and feel the history.",
    emoji: "🗽",
    budget: ["under25"],
    vibe: ["adventurous", "romantic"],
    setting: "outdoor",
    location: ["jersey-city"],
    dateType: "outdoors",
    venues: [
      { name: "Statue Cruises from Liberty State Park", address: "Liberty State Park, Jersey City, NJ", rating: 5, priceRange: "$24/person", googleMapsUrl: "https://maps.google.com/?q=Statue+Cruises+Liberty+State+Park", website: "https://www.statuecruises.com", highlight: "Departs from JC, shorter lines than Manhattan side" },
    ],
  },
  {
    id: "kayaking",
    title: "Kayaking on the Hudson",
    description: "Paddle together with the Manhattan skyline as your backdrop. Peaceful, scenic, and surprisingly romantic.",
    emoji: "🛶",
    budget: ["under75"],
    vibe: ["active", "adventurous"],
    setting: "outdoor",
    location: ["jersey-city", "manhattan"],
    dateType: "outdoors",
    venues: [
      { name: "Liberty Landing Marina", address: "80 Audrey Zapp Dr, Jersey City, NJ 07305", rating: 5, priceRange: "$40-60/couple", googleMapsUrl: "https://maps.google.com/?q=Liberty+Landing+Marina+Jersey+City", highlight: "Best launch point, Statue of Liberty views" },
      { name: "Manhattan Community Boathouse", address: "Pier 96, New York, NY", rating: 4, priceRange: "Free-$40/couple", googleMapsUrl: "https://maps.google.com/?q=Manhattan+Community+Boathouse", highlight: "Free kayaking weekends in summer! Bring your own life jacket" },
    ],
  },

  // ===== RELAXATION =====
  {
    id: "spa-day",
    title: "Spa Day Together",
    description: "Hot tubs, saunas, scrubs, and total bliss. The ultimate way to recharge as a couple.",
    emoji: "🧖",
    budget: ["splurge"],
    vibe: ["romantic", "cozy"],
    setting: "indoor",
    location: ["jersey-city", "manhattan"],
    dateType: "relaxation",
    venues: [
      { name: "Sojo Spa Club", address: "660 River Rd, Edgewater, NJ 07020", rating: 5, priceRange: "$80-150/person", googleMapsUrl: "https://maps.google.com/?q=Sojo+Spa+Club+Edgewater+NJ", website: "https://www.sojospaclub.com", highlight: "Korean spa, outdoor infinity pool with NYC skyline, incredible" },
      { name: "QC NY Spa", address: "Governors Island, New York, NY", rating: 5, priceRange: "$100-150/person", googleMapsUrl: "https://maps.google.com/?q=QC+NY+Spa+Governors+Island", highlight: "Italian spa on Governors Island, waterfront thermal baths" },
      { name: "Aire Ancient Baths", address: "88 Franklin St, New York, NY 10013", rating: 5, priceRange: "$100-180/person", googleMapsUrl: "https://maps.google.com/?q=Aire+Ancient+Baths+NYC", highlight: "Roman-style baths, candlelit, incredibly romantic" },
      { name: "Juvenex Spa", address: "25 W 32nd St, New York, NY 10001", rating: 4, priceRange: "$60-100/person", googleMapsUrl: "https://maps.google.com/?q=Juvenex+Spa+NYC", highlight: "K-town spa, open 24hrs, great couples packages" },
    ],
  },
  {
    id: "home-spa",
    title: "DIY Spa Night at Home",
    description: "Face masks, bath bombs, candles, and chill music. Give each other massages and unwind without leaving the house.",
    emoji: "🕯️",
    budget: ["free", "under25"],
    vibe: ["cozy", "romantic"],
    setting: "home",
    location: ["home"],
    dateType: "relaxation",
    venues: [
      { name: "Your place!", address: "Home", rating: 5, priceRange: "Free-$25", googleMapsUrl: "", highlight: "Zero commute, maximum comfort, total personalization" },
    ],
  },
  {
    id: "movie-fort",
    title: "Blanket Fort Movie Night",
    description: "Build a blanket fort, string fairy lights, and binge a movie trilogy with popcorn. Pure cozy magic.",
    emoji: "🏰",
    budget: ["free"],
    vibe: ["cozy"],
    setting: "home",
    location: ["home"],
    dateType: "relaxation",
    venues: [
      { name: "Your living room!", address: "Home", rating: 5, priceRange: "Free", googleMapsUrl: "", highlight: "Pillows, blankets, fairy lights, snacks — perfection" },
    ],
  },
  {
    id: "fancy-dinner-home",
    title: "Fancy Dinner at Home",
    description: "Dress up, candles, cloth napkins, three-course meal, soft jazz. All the romance, none of the restaurant prices.",
    emoji: "🕯️",
    budget: ["under25"],
    vibe: ["romantic", "creative"],
    setting: "home",
    location: ["home"],
    dateType: "relaxation",
    venues: [
      { name: "Your kitchen!", address: "Home", rating: 5, priceRange: "$20-30", googleMapsUrl: "", highlight: "Cook together, dress up, make it an event" },
    ],
  },
  {
    id: "cooking-class",
    title: "Cooking Class Together",
    description: "Learn to make pasta, sushi, or Thai food side by side. Leave with a new skill and a full belly.",
    emoji: "👨‍🍳",
    budget: ["under75", "splurge"],
    vibe: ["creative", "romantic"],
    setting: "indoor",
    location: ["jersey-city", "manhattan"],
    dateType: "food-experience",
    venues: [
      { name: "Sur La Table", address: "75 9th Ave, New York, NY 10011", rating: 5, priceRange: "$60-90/person", googleMapsUrl: "https://maps.google.com/?q=Sur+La+Table+Chelsea+Market", highlight: "Chelsea Market location, date night classes, pasta making" },
      { name: "Institute of Culinary Education", address: "225 Liberty St, New York, NY 10281", rating: 5, priceRange: "$80-120/person", googleMapsUrl: "https://maps.google.com/?q=Institute+of+Culinary+Education+NYC", website: "https://www.ice.edu", highlight: "Professional chefs teaching, Brookfield Place, top-tier" },
      { name: "Classpop! JC", address: "Jersey City, NJ", rating: 4, priceRange: "$50-80/person", googleMapsUrl: "https://maps.google.com/?q=cooking+class+Jersey+City", highlight: "Various local instructors, diverse cuisines, flexible scheduling" },
      { name: "The Brooklyn Kitchen", address: "100 Frost St, Brooklyn, NY 11211", rating: 4, priceRange: "$70-100/person", googleMapsUrl: "https://maps.google.com/?q=The+Brooklyn+Kitchen", highlight: "Hands-on, fun atmosphere, great for couples" },
    ],
  },

  // ===== NEW DINING IDEAS =====
  {
    id: "korean-bbq",
    title: "Korean BBQ Night",
    description: "Grill wagyu and prime cuts tableside, share banchan, and bond over sizzling meat. Interactive, delicious, and impossibly fun.",
    emoji: "🥩",
    budget: ["under75", "splurge"],
    vibe: ["adventurous", "romantic"],
    setting: "indoor",
    location: ["manhattan"],
    dateType: "dining",
    venues: [
      { name: "COTE Korean Steakhouse", address: "16 W 22nd St, New York, NY 10010", rating: 5, priceRange: "$130-160/couple", googleMapsUrl: "https://maps.google.com/?q=COTE+Korean+Steakhouse+New+York", website: "https://www.cotekoreansteakhouse.com", highlight: "Michelin-starred, Butcher's Feast with 4 wagyu cuts, egg soufflé & soft serve" },
      { name: "Gaonnuri", address: "1250 Broadway, 39th Floor, New York, NY 10001", rating: 4, priceRange: "$110-160/couple", googleMapsUrl: "https://maps.google.com/?q=Gaonnuri+New+York+City", website: "https://www.gaonnurinyc.com", highlight: "Korean BBQ on the 39th floor — panoramic Manhattan skyline views" },
      { name: "Jua", address: "36 E 22nd St, New York, NY 10010", rating: 5, priceRange: "$270/couple", googleMapsUrl: "https://maps.google.com/?q=Jua+New+York+City", website: "https://juanyc.com", highlight: "Michelin-starred 12-seat Korean tasting menu, book 3 weeks out at midnight" },
    ],
  },
  {
    id: "tapas-night",
    title: "Tapas & Small Plates",
    description: "Share a dozen plates, sip sangria, and graze your way through a romantic evening. Perfect for couples who love trying everything.",
    emoji: "🫒",
    budget: ["under75", "splurge"],
    vibe: ["romantic", "cozy"],
    setting: "indoor",
    location: ["manhattan"],
    dateType: "dining",
    venues: [
      { name: "Txikito", address: "240 Ninth Ave, New York, NY 10001", rating: 4, priceRange: "$62-100/couple", googleMapsUrl: "https://maps.google.com/?q=Txikito+Chelsea+New+York", website: "https://www.txikitonyc.com", highlight: "Authentic Basque pintxos, candle-lit wood-paneled Chelsea cabin" },
      { name: "Boqueria SoHo", address: "171 Spring St, New York, NY 10012", rating: 4, priceRange: "$80-120/couple", googleMapsUrl: "https://maps.google.com/?q=Boqueria+SoHo+New+York", website: "https://boqueriarestaurant.com/location/nyc/soho/", highlight: "Barcelona-style tapas, bacon-wrapped dates, lively SoHo energy" },
    ],
  },
  {
    id: "thai-date",
    title: "Thai Dinner Date",
    description: "Aromatic curries, fresh herbs, and bold flavors — Thai food is underrated for romance. Share pad kra pao and mango sticky rice.",
    emoji: "🍜",
    budget: ["under75"],
    vibe: ["cozy", "adventurous"],
    setting: "indoor",
    location: ["manhattan"],
    dateType: "dining",
    venues: [
      { name: "Wayla", address: "100 Forsyth St, New York, NY 10002", rating: 4, priceRange: "$70-100/couple", googleMapsUrl: "https://maps.google.com/?q=Wayla+Restaurant+New+York+City", website: "https://www.waylanyc.com", highlight: "Underground LES gem with secret garden, homestyle Bangkok cooking" },
    ],
  },
  {
    id: "indian-fine-dining",
    title: "Indian Fine Dining",
    description: "Bold spices, inventive plating, and flavors that blow your mind. NYC's Indian dining scene is world-class right now.",
    emoji: "🍛",
    budget: ["under75", "splurge"],
    vibe: ["romantic", "adventurous"],
    setting: "indoor",
    location: ["manhattan"],
    dateType: "dining",
    venues: [
      { name: "Semma", address: "60 Greenwich Ave, New York, NY 10011", rating: 5, priceRange: "$120-160/couple", googleMapsUrl: "https://maps.google.com/?q=Semma+New+York+City", website: "https://www.semma.nyc", highlight: "Michelin-starred, NYT #1 restaurant, James Beard-winning South Indian" },
      { name: "Adda", address: "107 1st Ave, New York, NY 10003", rating: 5, priceRange: "$80-120/couple", googleMapsUrl: "https://maps.google.com/?q=Adda+Indian+East+Village+New+York", website: "https://www.addanyc.com", highlight: "Time Out's #1 restaurant 2026, smoky Mumbai-inspired, bone marrow & goat roast" },
    ],
  },
  {
    id: "waterfront-dinner",
    title: "Waterfront Dinner in JC",
    description: "Candlelight, incredible food, and the Manhattan skyline glittering across the water. Jersey City's waterfront dining is next level.",
    emoji: "🌃",
    budget: ["splurge"],
    vibe: ["romantic"],
    setting: "indoor",
    location: ["jersey-city"],
    dateType: "dining",
    venues: [
      { name: "Battello", address: "502 Washington Blvd, Jersey City, NJ 07310", rating: 4, priceRange: "$120-160/couple", googleMapsUrl: "https://maps.google.com/?q=Battello+Jersey+City", website: "https://www.battellojc.com", highlight: "Dockside patio on the Hudson, Chef Ryan DePersio, JC's top proposal spot" },
      { name: "Lokal Eatery & Bar", address: "2 2nd St, Unit 101, Jersey City, NJ 07302", rating: 5, priceRange: "$80-120/couple", googleMapsUrl: "https://maps.google.com/?q=Lokal+Eatery+Bar+Jersey+City", website: "https://www.lokaljc.com", highlight: "Michelin-trained chef, global small plates, floor-to-ceiling skyline views" },
      { name: "87 Sussex", address: "87 Sussex St, Jersey City, NJ 07302", rating: 5, priceRange: "$100-150/couple", googleMapsUrl: "https://maps.google.com/?q=87+Sussex+Jersey+City", website: "https://87sussex.com", highlight: "Paulus Hook fine dining, Carabinero Prawns & Escargot Wontons" },
    ],
  },
  {
    id: "byob-italian",
    title: "BYOB Italian in Hoboken",
    description: "Bring your favorite wine, skip the markup, and enjoy incredible Italian food. Hoboken's BYOB scene is unbeatable.",
    emoji: "🍷",
    budget: ["under75"],
    vibe: ["romantic", "cozy"],
    setting: "indoor",
    location: ["hoboken"],
    dateType: "dining",
    venues: [
      { name: "Otto Strada", address: "743 Park Ave, Hoboken, NJ 07030", rating: 5, priceRange: "$46-70/couple", googleMapsUrl: "https://maps.google.com/?q=Otto+Strada+Hoboken", website: "https://www.ottostrada.com", highlight: "No-reservations BYOB, wood-fired oven, rivals NYC at a third of the price" },
      { name: "Anthony David's", address: "953 Bloomfield St, Hoboken, NJ 07030", rating: 4, priceRange: "$62-100/couple", googleMapsUrl: "https://maps.google.com/?q=Anthony+Davids+Hoboken", website: "https://anthonydavids.com", highlight: "25+ years of farm-to-table Italian, gorgeous patio, GF-friendly" },
      { name: "Grand Vin Kitchen & Bar", address: "500 Grand St, Hoboken, NJ 07030", rating: 5, priceRange: "$80-120/couple", googleMapsUrl: "https://maps.google.com/?q=Grand+Vin+Hoboken", website: "https://grandvinhoboken.com", highlight: "Hoboken's most beloved date spot, scallops, risotto, live acoustic music" },
    ],
  },
  {
    id: "tasting-menu",
    title: "Tasting Menu Experience",
    description: "Multi-course chef's tasting with wine pairing — a culinary journey that turns dinner into an event. Special occasion energy.",
    emoji: "👨‍🍳",
    budget: ["splurge"],
    vibe: ["romantic"],
    setting: "indoor",
    location: ["manhattan"],
    dateType: "dining",
    venues: [
      { name: "63 Clinton", address: "63 Clinton St, New York, NY 10002", rating: 5, priceRange: "$184/couple", googleMapsUrl: "https://maps.google.com/?q=63+Clinton+New+York+City", website: "https://www.63clinton.com", highlight: "Michelin-starred 7-course tasting for $92pp — NYC's best fine dining value" },
      { name: "Don Angie", address: "103 Greenwich Ave, New York, NY 10014", rating: 5, priceRange: "$120-160/couple", googleMapsUrl: "https://maps.google.com/?q=Don+Angie+New+York+City", website: "https://www.donangie.com", highlight: "Michelin-starred modern Italian, iconic pinwheel lasagna, blue-leather banquettes" },
      { name: "One if by Land, Two if by Sea", address: "17 Barrow St, New York, NY 10014", rating: 4, priceRange: "$390-400/couple", googleMapsUrl: "https://maps.google.com/?q=One+If+By+Land+Two+If+By+Sea+New+York", website: "https://www.oneifbyland.com", highlight: "NYC's most romantic restaurant — chandeliers, fireplaces, piano, Aaron Burr's carriage house" },
    ],
  },
  {
    id: "hidden-gem-jc",
    title: "Hidden Gem Dinner in JC",
    description: "Skip the hype and discover Jersey City's under-the-radar dining gems. Speakeasy vibes, craft cocktails, and incredible food.",
    emoji: "💎",
    budget: ["under75"],
    vibe: ["adventurous", "cozy"],
    setting: "indoor",
    location: ["jersey-city"],
    dateType: "dining",
    venues: [
      { name: "Dullboy", address: "364 Grove St, Jersey City, NJ 07302", rating: 4, priceRange: "$60-90/couple", googleMapsUrl: "https://maps.google.com/?q=Dullboy+Jersey+City", website: "https://www.dullboybar.com", highlight: "Speakeasy-inspired, Edison bulbs, craft cocktails, weekly movie nights" },
      { name: "The Roxy JC", address: "66 Monitor St, Jersey City, NJ 07304", rating: 4, priceRange: "$80-120/couple", googleMapsUrl: "https://maps.google.com/?q=The+Roxy+JC+Jersey+City", website: "https://www.theroxyjc.com", highlight: "Art Deco room, impeccable cocktails, moody & elegant atmosphere" },
      { name: "Corto", address: "464 Central Ave, Jersey City, NJ 07307", rating: 4, priceRange: "$40-60/couple", googleMapsUrl: "https://maps.google.com/?q=Corto+Jersey+City", highlight: "Rustic & authentic BYOB, cozy Heights gem, amazing pasta" },
    ],
  },

  // ===== NEW ACTIVITY IDEAS =====
  {
    id: "axe-throwing",
    title: "Axe Throwing Date",
    description: "Channel your inner lumberjack, talk trash, and see who can hit the bullseye. Surprisingly satisfying and hilarious together.",
    emoji: "🪓",
    budget: ["under75"],
    vibe: ["active", "adventurous"],
    setting: "indoor",
    location: ["manhattan", "jersey-city"],
    dateType: "adventure",
    venues: [
      { name: "Kick Axe Throwing", address: "622 Degraw St, Brooklyn, NY 11217", rating: 5, priceRange: "$70/couple", googleMapsUrl: "https://maps.google.com/?q=Kick+Axe+Throwing+Brooklyn+NY", website: "https://www.kickaxe.com/brooklyn", highlight: "The OG NYC axe bar — lodge vibes, full bar, coaches for beginners" },
      { name: "BEAT THE BOMB", address: "550 Washington Blvd, Jersey City, NJ", rating: 5, priceRange: "$50-70/couple", googleMapsUrl: "https://maps.google.com/?q=Beat+The+Bomb+Jersey+City", highlight: "Paint bomb finale, immersive tech, plus axe throwing lanes" },
    ],
  },
  {
    id: "glassblowing",
    title: "Glassblowing Class",
    description: "Shape molten glass into beautiful art together. The heat, the glow, the focus — it's mesmerizing and deeply romantic.",
    emoji: "🔥",
    budget: ["splurge"],
    vibe: ["creative", "romantic"],
    setting: "indoor",
    location: ["manhattan"],
    dateType: "arts-crafts",
    venues: [
      { name: "Brooklyn Glass", address: "142 13th St, Brooklyn, NY 11215", rating: 5, priceRange: "$250-400/couple", googleMapsUrl: "https://maps.google.com/?q=Brooklyn+Glass+Brooklyn+NY", website: "https://brooklynglass.com", highlight: "Couples class with 25+ year instructor, take your creation home" },
      { name: "UrbanGlass", address: "647 Fulton St, Brooklyn, NY 11217", rating: 5, priceRange: "$250+/couple", googleMapsUrl: "https://maps.google.com/?q=UrbanGlass+Brooklyn+NY", website: "https://urbanglass.org", highlight: "Largest public-access glass art facility in the NYC metro area" },
    ],
  },
  {
    id: "candle-making",
    title: "Candle Making Workshop",
    description: "Choose your scents, pour your wax, and create custom candles together. Sip wine while your apartment starts smelling amazing.",
    emoji: "🕯️",
    budget: ["under75"],
    vibe: ["creative", "cozy", "romantic"],
    setting: "indoor",
    location: ["manhattan"],
    dateType: "arts-crafts",
    venues: [
      { name: "ClassBento Candle Making", address: "Various Manhattan locations", rating: 5, priceRange: "$80-120/couple", googleMapsUrl: "https://maps.google.com/?q=ClassBento+Candle+Making+NYC", website: "https://classbento.com/candle-making-classes-new-york-city", highlight: "Sip-and-pour format, choose your own scents, BYOB wine" },
    ],
  },
  {
    id: "trapeze",
    title: "Trapeze Flying Lesson",
    description: "Fly through the air on a real trapeze over the Hudson River. Terrifying, exhilarating, and one of NYC's most unforgettable dates.",
    emoji: "🎪",
    budget: ["splurge"],
    vibe: ["adventurous", "active"],
    setting: "outdoor",
    location: ["manhattan"],
    dateType: "adventure",
    venues: [
      { name: "Trapeze School New York", address: "353 West St, New York, NY 10014", rating: 4, priceRange: "$140-160/couple", googleMapsUrl: "https://maps.google.com/?q=Trapeze+School+New+York+353+West+St", website: "https://newyork.trapezeschool.com", highlight: "Fly over the Hudson River, total beginners catch mid-air on first lesson" },
      { name: "Circus Academy NY", address: "Pier 40, Hudson River Park, NY 10014", rating: 5, priceRange: "$140/couple", googleMapsUrl: "https://maps.google.com/?q=Circus+Academy+NY+Pier+40+Hudson+River+Park", website: "https://www.circusacademy.com", highlight: "Couples circus night — trapeze, juggling, and aerial arts on a pier rooftop" },
    ],
  },
  {
    id: "dance-class",
    title: "Couples Dance Class",
    description: "Learn salsa, tango, or swing together. Step on each other's toes, laugh, and leave with a new skill you'll use forever.",
    emoji: "💃",
    budget: ["under25", "under75"],
    vibe: ["romantic", "active"],
    setting: "indoor",
    location: ["manhattan"],
    dateType: "entertainment",
    venues: [
      { name: "Dance Manhattan", address: "Chelsea, Manhattan", rating: 5, priceRange: "$30-50/couple", googleMapsUrl: "https://maps.google.com/?q=Dance+Manhattan+Studio+NYC", website: "http://www.dancemanhattan.com", highlight: "Salsa, tango, swing — one-day crash courses perfect for date night" },
      { name: "Dance With Me Studios", address: "37 West 37th St, 2nd Floor, New York, NY 10018", rating: 4, priceRange: "$40-60/couple", googleMapsUrl: "https://maps.google.com/?q=Dance+With+Me+Studio+Midtown+New+York", website: "https://dancewithmeusa.com", highlight: "6-dance crash course (waltz, foxtrot, tango, swing, rumba, cha-cha)" },
    ],
  },
  {
    id: "immersive-theater",
    title: "Immersive Theater Night",
    description: "Step into the show — solve mysteries, eat dinner, and become part of the story. Unlike anything you've ever experienced.",
    emoji: "🎭",
    budget: ["under75", "splurge"],
    vibe: ["adventurous", "creative"],
    setting: "indoor",
    location: ["manhattan"],
    dateType: "entertainment",
    venues: [
      { name: "BATSU! NYC", address: "East Village, Manhattan", rating: 5, priceRange: "$120-160/couple", googleMapsUrl: "https://maps.google.com/?q=BATSU+NYC+East+Village", website: "https://www.batsushownyc.com", highlight: "Japanese comedy game show dinner theater — enter through a speakeasy mural" },
      { name: "Accomplice NYC", address: "Greenwich Village, Manhattan", rating: 4, priceRange: "$80-100/couple", googleMapsUrl: "https://maps.google.com/?q=Accomplice+Theater+NYC+Greenwich+Village", website: "https://www.accomplicetheshow.com", highlight: "2-hour street mystery — become detectives solving clues through real NYC streets" },
    ],
  },
  {
    id: "museum-date",
    title: "Museum Date Night",
    description: "Wander through centuries of art, whisper about your favorites, and find hidden gems together. Late nights are extra romantic.",
    emoji: "🏛️",
    budget: ["under25", "under75"],
    vibe: ["romantic", "cozy"],
    setting: "indoor",
    location: ["manhattan"],
    dateType: "entertainment",
    venues: [
      { name: "The Met (Friday/Saturday Late Night)", address: "1000 Fifth Ave, New York, NY 10028", rating: 5, priceRange: "$60/couple", googleMapsUrl: "https://maps.google.com/?q=The+Metropolitan+Museum+of+Art+New+York", website: "https://www.metmuseum.org", highlight: "Open until 9pm Fri/Sat, live music, cocktails, rooftop garden bar (seasonal)" },
      { name: "The Met Cloisters", address: "99 Margaret Corbin Dr, Fort Tryon Park, NY 10040", rating: 5, priceRange: "$60/couple", googleMapsUrl: "https://maps.google.com/?q=The+Met+Cloisters+Fort+Tryon+Park+New+York", website: "https://www.metmuseum.org/visit/met-cloisters", highlight: "Hidden medieval monastery on a Hudson cliff — tapestry gardens, peaceful cloisters" },
    ],
  },
  {
    id: "distillery-tour",
    title: "Whiskey Distillery Tour",
    description: "Tour a working distillery, taste craft whiskey, and end the night at their underground speakeasy. Sophisticated and fun.",
    emoji: "🥃",
    budget: ["under75"],
    vibe: ["adventurous", "cozy"],
    setting: "indoor",
    location: ["manhattan"],
    dateType: "drinks",
    venues: [
      { name: "Great Jones Distilling Co.", address: "686 Broadway, New York, NY 10012", rating: 4, priceRange: "$72/couple", googleMapsUrl: "https://maps.google.com/?q=Great+Jones+Distilling+Company+New+York+NY", website: "https://greatjonesdistillingco.com", highlight: "Manhattan's first legal whiskey distillery in 100+ years, underground speakeasy" },
    ],
  },

  // ===== NEW OUTDOOR & SEASONAL IDEAS =====
  {
    id: "botanical-garden",
    title: "Botanical Garden Visit",
    description: "Wander through stunning gardens, discover exotic plants, and find quiet benches to sit and talk. Peak romance during cherry blossom season.",
    emoji: "🌸",
    budget: ["under25", "under75"],
    vibe: ["romantic", "cozy"],
    setting: "outdoor",
    location: ["manhattan"],
    dateType: "outdoors",
    venues: [
      { name: "Brooklyn Botanic Garden", address: "990 Washington Ave, Brooklyn, NY 11225", rating: 5, priceRange: "$44/couple", googleMapsUrl: "https://maps.google.com/?q=Brooklyn+Botanic+Garden", website: "https://www.bbg.org", highlight: "200+ cherry trees, CherryWatch tracker, peak bloom late April" },
      { name: "New York Botanical Garden", address: "2900 Southern Blvd, Bronx, NY 10458", rating: 5, priceRange: "$70-78/couple", googleMapsUrl: "https://maps.google.com/?q=New+York+Botanical+Garden+Bronx", website: "https://www.nybg.org", highlight: "250 acres, Orchid Nights with live music & cocktails in the glasshouse" },
    ],
  },
  {
    id: "high-line-walk",
    title: "High Line Walk & Chelsea",
    description: "Stroll the elevated park, admire rotating art installations, lounge on the Sundeck, then explore Chelsea galleries and markets.",
    emoji: "🌿",
    budget: ["free"],
    vibe: ["romantic", "cozy"],
    setting: "outdoor",
    location: ["manhattan"],
    dateType: "outdoors",
    venues: [
      { name: "The High Line", address: "Gansevoort St to W 34th St, Manhattan", rating: 5, priceRange: "Free", googleMapsUrl: "https://maps.google.com/?q=The+High+Line+New+York", website: "https://www.thehighline.org", highlight: "1.45-mile elevated park, Sundeck with Hudson views, art installations" },
      { name: "Chelsea Market", address: "75 9th Ave, New York, NY 10011", rating: 5, priceRange: "$20-40/couple", googleMapsUrl: "https://maps.google.com/?q=Chelsea+Market+NYC", highlight: "Right below the High Line — lobster, tacos, baked goods, browsing" },
    ],
  },
  {
    id: "bookstore-date",
    title: "Bookstore & Café Date",
    description: "Browse shelves together, pick books for each other, and linger over coffee. Low-key, intimate, and endlessly charming.",
    emoji: "📚",
    budget: ["free", "under25"],
    vibe: ["cozy", "romantic"],
    setting: "indoor",
    location: ["manhattan"],
    dateType: "relaxation",
    venues: [
      { name: "McNally Jackson", address: "134 Prince St, New York, NY 10012", rating: 5, priceRange: "Free-$20", googleMapsUrl: "https://maps.google.com/?q=McNally+Jackson+134+Prince+Street+New+York", website: "https://www.mcnallyjackson.com", highlight: "SoHo's premier indie bookstore, reading nooks, in-store café, author events" },
      { name: "Yu & Me Books", address: "44 Mulberry St, New York, NY 10013", rating: 5, priceRange: "Free-$15", googleMapsUrl: "https://maps.google.com/?q=Yu+and+Me+Books+Chinatown+New+York", website: "https://www.yuandmebooks.com", highlight: "First Asian woman-owned bookstore in NYC, espresso + wine + beer" },
      { name: "The Lit Bar", address: "131 Alexander Ave, Bronx, NY 10454", rating: 5, priceRange: "Free-$15", googleMapsUrl: "https://maps.google.com/?q=The+Lit+Bar+Bronx+New+York", website: "https://www.thelitbar.com", highlight: "Curated bookstore with wine bar, warm atmosphere, cross-borough adventure" },
    ],
  },
  {
    id: "ice-skating",
    title: "Ice Skating Date",
    description: "Hold hands, glide together, and warm up with hot chocolate. Classic winter romance at its finest.",
    emoji: "⛸️",
    budget: ["under25"],
    vibe: ["romantic", "active"],
    setting: "outdoor",
    location: ["jersey-city", "manhattan"],
    dateType: "outdoors",
    venues: [
      { name: "Newport Skates", address: "95 River Drive South, Jersey City, NJ 07310", rating: 4, priceRange: "$40/couple", googleMapsUrl: "https://maps.google.com/?q=Newport+Skates+Jersey+City", website: "https://www.newportskates.com", highlight: "Outdoor rink with unobstructed Manhattan skyline views, Nov-Mar" },
      { name: "Wollman Rink Central Park", address: "Central Park, New York, NY", rating: 5, priceRange: "$30-50/couple", googleMapsUrl: "https://maps.google.com/?q=Wollman+Rink+Central+Park+New+York", highlight: "Iconic NYC skating with Midtown skyline backdrop" },
    ],
  },
  {
    id: "sunset-cruise",
    title: "Sunset Sail on the Hudson",
    description: "Board a vintage yacht, sip cocktails, and watch the sun set behind the Statue of Liberty. Pure magic on the water.",
    emoji: "⛵",
    budget: ["splurge"],
    vibe: ["romantic"],
    setting: "outdoor",
    location: ["manhattan", "jersey-city"],
    dateType: "adventure",
    venues: [
      { name: "Classic Harbor Line", address: "62 Chelsea Piers, Pier 62, New York, NY 10011", rating: 5, priceRange: "$252-296/couple", googleMapsUrl: "https://maps.google.com/?q=Classic+Harbor+Line+Chelsea+Piers+New+York", website: "https://sail-nyc.com", highlight: "1920s yacht, Statue of Liberty at golden hour, tapas & cocktails, 4.8★" },
      { name: "Sea the City", address: "Liberty Landing Marina, Jersey City, NJ 07305", rating: 5, priceRange: "$100-180/couple", googleMapsUrl: "https://maps.google.com/?q=Sea+the+City+Liberty+Landing+Marina", website: "https://www.seathecity.com", highlight: "Hot tub boat or pontoon BYOB cruise from JC, Statue of Liberty views" },
    ],
  },
  {
    id: "speakeasy-jc",
    title: "JC Speakeasy Crawl",
    description: "Discover Jersey City's hidden bars — secret staircases, bookshelf doors, and no-sign entrances. Dress up and hunt them down together.",
    emoji: "🗝️",
    budget: ["under75"],
    vibe: ["adventurous", "romantic"],
    setting: "indoor",
    location: ["jersey-city", "hoboken"],
    dateType: "drinks",
    venues: [
      { name: "143 Social", address: "143 Newark Ave, Jersey City, NJ 07302", rating: 4, priceRange: "$60-100/couple", googleMapsUrl: "https://maps.google.com/?q=143+Social+Jersey+City", website: "https://www.143social.com", highlight: "Enter through Better Days burger spot, descend to 1920s basement glamour" },
      { name: "Don't Tell Liv", address: "138 Newark Ave, 2nd Floor, Jersey City, NJ 07302", rating: 4, priceRange: "$60-80/couple", googleMapsUrl: "https://maps.google.com/?q=Don't+Tell+Liv+138+Newark+Avenue+Jersey+City", website: "https://livjc.com", highlight: "Opened 2025, upstairs speakeasy lounge, DJ nights, craft cocktails" },
      { name: "Junto Attic Bar", address: "68 Mercer Street, Jersey City, NJ 07302", rating: 4, priceRange: "$50-70/couple", googleMapsUrl: "https://maps.google.com/?q=Franklin+Social+Jersey+City+Junto+Attic+Bar", highlight: "Hidden above Franklin Social, groups of 4 or fewer only, first-come basis" },
      { name: "Perico", address: "36-42 Newark Street, Hoboken, NJ 07030", rating: 4, priceRange: "$60-80/couple", googleMapsUrl: "https://maps.google.com/?q=Panela+Restaurant+Hoboken+Newark+Street", highlight: "Enter through secret bookshelf in Panela restaurant, Frank Sinatra's old haunt" },
    ],
  },
  {
    id: "farmers-market",
    title: "Farmers Market Date",
    description: "Stroll through vendors, taste local honey, pick up flowers and fresh bread. Then cook something amazing together at home.",
    emoji: "🌻",
    budget: ["free", "under25"],
    vibe: ["cozy", "romantic"],
    setting: "outdoor",
    location: ["jersey-city", "hoboken"],
    dateType: "outdoors",
    venues: [
      { name: "Grove Street PATH Farmers Market", address: "Grove Street PATH Plaza, Jersey City, NJ", rating: 5, priceRange: "Free-$50", googleMapsUrl: "https://maps.google.com/?q=Grove+Street+PATH+Plaza+Jersey+City+Farmers+Market", highlight: "25+ vendors, artisan bread, fresh flowers, local honey, Apr-Dec" },
      { name: "Hamilton Park Farmers Market", address: "8th St & McWilliams Place, Jersey City, NJ", rating: 4, priceRange: "Free-$40", googleMapsUrl: "https://maps.google.com/?q=Hamilton+Park+Farmers+Market+Jersey+City", highlight: "Live music, neighborhood charm, Wednesday evenings May-Dec" },
      { name: "Hoboken Uptown Farmers Market", address: "Under the 14th St Viaduct, Hoboken, NJ", rating: 4, priceRange: "Free-$40", googleMapsUrl: "https://maps.google.com/?q=Hoboken+Uptown+Farmers+Market+14th+Street+Viaduct", highlight: "Saturday mornings under a dramatic viaduct, combine with waterfront walk" },
    ],
  },
  {
    id: "night-market",
    title: "Night Market Food Adventure",
    description: "100+ food vendors from every corner of the world, all for $4-6 per dish. The most diverse and delicious date in NYC.",
    emoji: "🏮",
    budget: ["under25"],
    vibe: ["adventurous", "active"],
    setting: "outdoor",
    location: ["manhattan"],
    dateType: "food-experience",
    venues: [
      { name: "Queens Night Market", address: "47-01 111th St, Queens, NY 11368", rating: 5, priceRange: "$20-40/couple", googleMapsUrl: "https://maps.google.com/?q=Queens+Night+Market+Flushing+Queens", website: "https://www.queensnightmarket.com", highlight: "Free entry, 100+ vendors, Saturday nights Apr-Oct, incredible global food" },
    ],
  },
  {
    id: "cooking-class-hoboken",
    title: "Cooking Class in Hoboken",
    description: "Cook side-by-side in a beautiful studio with Manhattan skyline views. Hands-on, seasonal menus, and you eat everything you make.",
    emoji: "🍳",
    budget: ["under75", "splurge"],
    vibe: ["creative", "romantic"],
    setting: "indoor",
    location: ["hoboken"],
    dateType: "food-experience",
    venues: [
      { name: "Hudson Table", address: "1403 Clinton St, Hoboken, NJ 07030", rating: 4, priceRange: "$100-180/couple", googleMapsUrl: "https://maps.google.com/?q=Hudson+Table+Hoboken+NJ", website: "https://hudsontable.com/hoboken/", highlight: "Interactive culinary studio, skyline views, rotating seasonal menus" },
    ],
  },
  {
    id: "sculpture-garden",
    title: "Hidden Garden & Sculpture Walk",
    description: "Discover secret gardens and outdoor sculptures tucked away in the city. Quiet, romantic, and totally free.",
    emoji: "🗿",
    budget: ["free"],
    vibe: ["romantic", "cozy"],
    setting: "outdoor",
    location: ["manhattan", "hoboken"],
    dateType: "outdoors",
    venues: [
      { name: "Elizabeth Street Garden", address: "209-211 Elizabeth St, New York, NY 10012", rating: 5, priceRange: "Free", googleMapsUrl: "https://maps.google.com/?q=Elizabeth+Street+Garden+Nolita+New+York", website: "https://elizabethstreetgarden.org", highlight: "Hidden Nolita sculpture garden, antique stonework, Manhattan's best-kept secret" },
      { name: "Pier A Park", address: "Sinatra Drive, Hoboken, NJ 07030", rating: 5, priceRange: "Free", googleMapsUrl: "https://maps.google.com/?q=Pier+A+Park+Hoboken+NJ", highlight: "Hoboken's best sunset spot — quiet, uncrowded, unobstructed skyline views" },
    ],
  },
  {
    id: "stargazing",
    title: "Stargazing Night Trip",
    description: "Escape the city lights, set up a blanket, and gaze at the stars together. Telescopes, constellations, and shooting stars.",
    emoji: "🌌",
    budget: ["free", "under25"],
    vibe: ["romantic", "adventurous"],
    setting: "outdoor",
    location: ["jersey-city"],
    dateType: "outdoors",
    venues: [
      { name: "Jenny Jump State Forest Observatory", address: "333 State Park Rd, Great Meadows, NJ 07844", rating: 5, priceRange: "Free", googleMapsUrl: "https://maps.google.com/?q=Jenny+Jump+State+Forest+Great+Meadows+NJ", website: "https://uacnj.org", highlight: "NJ's best stargazing — 7 telescopes, free presentations, Saturdays Apr-Oct" },
      { name: "Wawayanda State Park", address: "885 Warwick Turnpike, Hewitt, NJ 07421", rating: 4, priceRange: "$5-7/parking", googleMapsUrl: "https://maps.google.com/?q=Wawayanda+State+Park+Hewitt+NJ", highlight: "Dark skies near NJ/NY border, astronomy club events, night hiking trails" },
    ],
  },
  {
    id: "free-kayaking",
    title: "Free Kayaking on the Hudson",
    description: "Paddle for free on the Hudson with the Manhattan skyline as your backdrop. Yes, actually free. Summer's best-kept secret.",
    emoji: "🛶",
    budget: ["free"],
    vibe: ["active", "adventurous"],
    setting: "outdoor",
    location: ["hoboken", "manhattan"],
    dateType: "outdoors",
    venues: [
      { name: "Hoboken Cove Community Boathouse", address: "Maxwell Place Park, 1100 Sinatra Dr N, Hoboken, NJ 07030", rating: 5, priceRange: "Free", googleMapsUrl: "https://maps.google.com/?q=Hoboken+Cove+Community+Boathouse", website: "http://www.hobokencoveboathouse.org", highlight: "Free kayaks, paddleboards & canoes, Memorial Day-fall, paddle toward Manhattan" },
      { name: "Manhattan Community Boathouse", address: "Pier 96, New York, NY", rating: 4, priceRange: "Free", googleMapsUrl: "https://maps.google.com/?q=Manhattan+Community+Boathouse", highlight: "Free kayaking weekends in summer, bring your own life jacket" },
    ],
  },
  {
    id: "rowboat-central-park",
    title: "Rowboat in Central Park",
    description: "Row your own boat across the lake, drift under bridges, and pretend you're in a movie. Timeless, simple, deeply romantic.",
    emoji: "🚣",
    budget: ["under25"],
    vibe: ["romantic", "cozy"],
    setting: "outdoor",
    location: ["manhattan"],
    dateType: "outdoors",
    venues: [
      { name: "Central Park Boathouse", address: "East Drive at E. 72nd Street, Central Park, NY", rating: 4, priceRange: "$25-60/couple", googleMapsUrl: "https://maps.google.com/?q=Central+Park+Boathouse+New+York", website: "https://centralparkboathouse.com", highlight: "Row past Bow Bridge, no reservations needed, Apr-Oct" },
    ],
  },
];
